# Test and build & push the docker image

name: Backend test

on:
  pull_request:
    paths:
      - 'loyalty-backend/**'
  push:
    paths:
      - 'loyalty-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_ORG_PACKAGES }}" > ~/.npmrc
      - name: NPM CI
        run: npm ci
        working-directory: loyalty-backend
      - name: Build
        run: npm run build --if-present
        working-directory: loyalty-backend
      - name: Test
        run: npm test
        env:
          CI: true
          # A random string for testing
          JWT_SECRET: "D943E42E91D22C87621BAB73F866EDAA0FA0178B25C98EC54C254F897A609F5C"
        working-directory: loyalty-backend
    services:
      mongodb:
        image: mongo:4.2.3
        ports:
          - 27017:27017

  push-docker:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/develop'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./loyalty-backend
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/loyalty-backend:develop
          build-args: |
            NPM_TOKEN=${{ secrets.READ_ORG_PACKAGES }}
