# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: loyalty-campaigns test and publish

on:
  pull_request:
    paths:
      - 'campaigns/**'
  push:
    paths:
      - 'campaigns/**'
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: NPM CI
        run: npm ci
        working-directory: loyalty-campaigns
      - name: Build
        run: npm run build --if-present
        working-directory: loyalty-campaigns
      - name: Test
        run: npm test
        env:
          CI: true
        working-directory: loyalty-campaigns

  publish-gpr:
    needs: test
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: NPM CI
        run: npm ci
        working-directory: loyalty-campaigns
      - name: Test
        run: npm test
        working-directory: loyalty-campaigns
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: loyalty-campaigns
