# Test and build & push the docker image

name: loyalty-app (PWA) tests

on:
  pull_request:
    paths:
      - 'loyalty-app/**'
  push:
    paths:
      - 'loyalty-app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn install
        working-directory: loyalty-app
      - name: Test
        run: yarn test
        working-directory: loyalty-app
  push-docker:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/develop'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./loyalty-app
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/loyalty-app:develop

