name: loyalty-panel test and deploy

on:
  pull_request:
    paths:
      - 'panel/**'
  push:
    paths:
      - 'panel/**'
      - '.github/workflows/panel.ci-cd.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_ORG_PACKAGES }}" > ~/.npmrc
      - name: NPM CI
        run: npm ci
        working-directory: panel
      - name: Test
        run: npm test
        env:
          CI: true
        working-directory: panel
  deploy-s3:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.READ_ORG_PACKAGES }}" > ~/.npmrc
      - name: npm ci and build
        run: npm ci && npm run build
        working-directory: panel
      - name: Deploy to S3 bucket
        run: aws s3 sync ./build s3://panel-getloyaltyapp --delete
        working-directory: panel
  push-docker-dev:
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/develop'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./panel
          build-args: NPM_TOKEN=${{secrets.READ_ORG_PACKAGES}}
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_URL }}/loyalty-panel:develop
