name: scanner-app test

on:
  pull_request:
    paths:
      - 'scanner-app/**'
  push:
    paths:
      - 'scanner-app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - name: Pub get
        run: flutter pub get
        working-directory: scanner-app
      - name: Test
        run: flutter test
        working-directory: scanner-app
      - name: Build apk
        run: flutter build apk
        working-directory: scanner-app
  release:
    needs: test
    name: Build APK
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - name: Pub get
        run: flutter pub get
        working-directory: scanner-app
      - name: Test
        run: flutter test
        working-directory: scanner-app
      - name: Build apk
        run: flutter build apk # --split-per-abi
        working-directory: scanner-app
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "scanner-app/build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
